data_cfg:
  dataset_name: GREW-office-64pixel
  dataset_root:
    silhouette_root: /8T/xiongjianbo/dataset/GREW/GREW-64-44-pkl
    smpl_root: /8T/xiongjianbo/dataset/GREW/GREW-ske-pkl
  dataset_partition: ./misc/partitions/GREW_office_split.json
  num_workers: 16
  remove_no_gallery: false
  test_dataset_name: GREW-office-split

evaluator_cfg:
  enable_float16: false
  restore_ckpt_strict: true
  restore_hint: 180000
  save_name: MCDGait_GREW
  eval_func: evaluation_GREW
  submission_path: ./misc/GREW_submission/submission.csv
  sampler:
    plus_smpl: true
    batch_shuffle: false
    batch_size: 2
    sample_type: all_ordered # all indicates whole sequence used to test, while ordered means input sequence by its natural order; Other options:   fixed_unordered
    frames_all_limit: 720 # limit the number of sampled frames to prevent out of memory
  metric: euc # cos euc
  transform:
    - type: BaseSilTransform

loss_cfg:
- log_prefix: triplet
  loss_term_weight: 1.0
  margin: 0.2
  type: TripletLoss
  work_iteration: 0
- log_prefix: triplet_sil
  loss_term_weight: 1.0
  margin: 0.2
  type: TripletLoss
  work_iteration: 0
- log_prefix: triplet_ske
  loss_term_weight: 1.0
  margin: 0.2
  type: TripletLoss
  work_iteration: 0
- log_prefix: ctl_sil
  loss_term_weight: 0.5
  type: CTL_Loss
- log_prefix: ctl_ske
  loss_term_weight: 0.5
  type: CTL_Loss

model_cfg:
  model: MCDGait_GREW
  img_channals:
  - 1
  - 32
  - 64
  - 128
  - 256

  ske_channals:
  - 3
  - 32
  - 64
  - 128
  - 256

  hidden_dim: 256
  part_img: 16
  part_ske: 17
  class_num: 20000
  edge_importance_weighting: True

optimizer_cfg:
  lr: 0.0001
  momentum: 0.9
  solver: Adam
  weight_decay: 0

scheduler_cfg:
  gamma: 0.1
  milestones:
    - 60000
    - 120000
  scheduler: MultiStepLR

trainer_cfg:
  enable_float16: true
  log_iter: 100
  restore_ckpt_strict: true
  restore_hint: 0
  save_iter: 10000
  save_name: MCDGait_GREW
  sync_BN: false
  total_iter: 180000
  sampler:
    plus_smpl: true
    batch_shuffle: true
    batch_size:
      - 32
      - 4
    frames_num_fixed: 60
    frames_skip_num: 0
    sample_type: fixed_ordered
    type: TripletSampler
  transform:
    - type: BaseSilTransform